FROM nginx:latest

# Install Certbot and its Nginx plugin
RUN apt-get update && \
    apt-get install -y certbot python3-certbot-nginx && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy your Nginx configuration file into the container
COPY ./docker/nginx.conf /etc/nginx/nginx.conf

# Expose the necessary ports for HTTP and HTTPS
EXPOSE 80 443

# Run Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
