name: CI/CD Deployment pipeline

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add known hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Deploy application
      run: |
        ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} 'bash -s' << 'EOF'
        cd /var/www/${{ vars.DEPLOY_PATH }} || exit
        git pull origin staging
        sudo docker compose down --rmi all
        sudo docker compose pull
        sudo docker compose up -d --build
        EOF
